objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project_Member__c.object
<CustomObject>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Members</relationshipLabel>
        <relationshipName>Project_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Member</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Project Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>is_Timer_On__c</fullName>
        <label>is Timer On</label>
        <summaryFilterItems>
            <field>Time_Entry__c.is_Timer_active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Time_Entry__c.Task__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Logged_Time__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Logged Time</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Member</label>
        <referenceTo>Project_Member__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Timer_Started__c</fullName>
        <label>Timer Started</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>is_Timer_active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>is Timer active</label>
        <type>Checkbox</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <label>WorkLog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TimeTrackerComponentController.cls
public class TimeTrackerComponentController {

    @AuraEnabled
    public static List<Project__c> getProjects() {
        return [SELECT id, name,createddate, (SELECT id, name, is_Timer_On__c FROM Tasks__r ORDER BY name) 
                FROM Project__c WHERE Id IN 
                (SELECT Project__c FROM Project_Member__c WHERE Member__c = :UserInfo.getUserId()) 
                LIMIT 50];
    }
    
    @AuraEnabled
    public static void startTimer(String taskId) {
        String selectedId = taskId.substring(0, 15);
        Time_Entry__c entry = new Time_Entry__c(Date__c=Date.today(),Logged_Time__c=0, Task__c=(Id)selectedId,
                                               is_Timer_active__c=true,Timer_Started__c=DateTime.now());
        insert entry;

    }    

    @AuraEnabled
    public static void stopTimer(String taskId) {      
        List<Time_Entry__c> entries = [SELECT Id,Logged_Time__c,is_Timer_active__c,Timer_Started__c
                                       FROM Time_Entry__c WHERE is_Timer_active__c=true AND Task__c=:taskId
                                      AND Date__c=:Date.today()];
        for(Time_Entry__c entry: entries) {
            Decimal loggedMinutes = (DateTime.now().getTime() - entry.Timer_Started__c.getTime())/60000;
            entry.Logged_Time__c += loggedMinutes;
            entry.is_Timer_active__c=false;
            entry.Timer_Started__c=null;
        }
        update entries;
    }    
  
}