objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project_Member__c.object
<CustomObject>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Members</relationshipLabel>
        <relationshipName>Project_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Member</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Project Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Logged_Time__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Logged Time</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Owner_Id__c</fullName>
        <formula>Task__r.OwnerId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Owner Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Member</label>
        <referenceTo>Project_Member__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Manager__c</fullName>
        <formula>CASESAFEID(Task__r.OwnerId)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Related Manager</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_Project__c</fullName>
        <formula>Task__r.Project__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Related Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Weekly_Timesheet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Weekly Timesheet</label>
        <referenceTo>Weekly_Timesheet__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>is_Locked__c</fullName>
        <formula>Weekly_Timesheet__r.Locked__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>is Locked</label>
        <type>Checkbox</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <label>WorkLog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Weekly_Timesheet__c.object
<CustomObject>
    <fields>
        <fullName>Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Total_Time__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Time</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Weekly_Id__c</fullName>
        <externalId>true</externalId>
        <label>Weekly Id</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Weekly Timesheet</label>
    <nameField>
        <label>Weekly Timesheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weekly Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TimeEntryTriggerHandler.cls
public class TimeEntryTriggerHandler {
    
    public static void checkIsUserAllowedToAddEntry(List<Time_Entry__c> entries) {
        Set<Id> projectIds = new Set<Id>();
        for(Time_Entry__c entry: entries) {
            projectIds.add(entry.Related_Project__c);  
        }
      
        Map<Id,Project__c> projects = new Map<Id,Project__c>([SELECT Id, (SELECT Id, Member__c FROM Project_Members__r) 
                                    FROM Project__c WHERE Id IN:projectIds]);
        for(Time_Entry__c entry: entries) {
            Project__c project = projects.get(entry.Related_Project__c);
            Boolean error = true;
	        for(Project_Member__c member: project.Project_Members__r) {

                if(member.Member__c == entry.Owner_Id__c) error=false;
            }
            if(error) entry.addError(Label.Not_Project_Member);
        }        
    }

    public static void addEntryToTimesheet(List<Time_Entry__c> entries) {
        Set<String> timesheetIds = new Set<String>();

        for(Time_Entry__c entry: entries) {      
            String properTimesheet = Datetime.newInstance(entry.Date__c.toStartOfWeek(), 
                                     Time.newInstance(12, 0,0,0)).format('w') +' '+(Id)entry.Related_Manager__c;
            timesheetIds.add(properTimesheet);            
        }
        List<Weekly_Timesheet__c> timesheets = [SELECT Id, Weekly_Id__c, Locked__c FROM Weekly_Timesheet__c 
                                                WHERE Weekly_Id__c IN :timesheetIds];
        Map<String,Weekly_Timesheet__c> timesheetsById = new Map<String,Weekly_Timesheet__c>();
        for(Weekly_Timesheet__c timesheet: timesheets) {
            timesheetsById.put(timesheet.Weekly_Id__c,timesheet);
        }
        for(Time_Entry__c entry: entries) {
            String properTimesheet = Datetime.newInstance(entry.Date__c.toStartOfWeek(), 
                                     Time.newInstance(12, 0,0,0)).format('w') +' '+(Id)entry.Related_Manager__c;
            try {
                Weekly_Timesheet__c timesheet = timesheetsById.get(properTimesheet);
                if(timesheet.Locked__c==false) entry.Weekly_Timesheet__c = timesheet.Id;
                else entry.addError(Label.Timesheet_is_locked);
            } catch(Exception ex) {
				entry.addError(Label.Timesheet_not_found);            
            }
        }
    }
    
    public static void prohibitActionIfTimesheetIsLocked(List<Time_Entry__c> entries) {
        for(Time_Entry__c entry: entries) {
        	if(entry.is_Locked__c) entry.addError(Label.Timesheet_is_locked);
        }
    }
    
    public static void incrementTotalsOnTimesheet(List<Time_Entry__c> entries) {
        Set<Id> timesheetIds = new Set<Id>();
        for(Time_Entry__c entry: entries) {
            timesheetIds.add(entry.Weekly_Timesheet__c);        
        }  
        Map<Id,Weekly_Timesheet__c> timesheets = new Map<Id,Weekly_Timesheet__c> ([SELECT Id, 	Total_Time__c FROM Weekly_Timesheet__c 
                                                WHERE Id IN :timesheetIds]);
        for(Time_Entry__c entry: entries) {
            Weekly_Timesheet__c timesheet = timesheets.get(entry.Weekly_Timesheet__c);    
            if(timesheet.Total_Time__c==null) timesheet.Total_Time__c=0;
            timesheet.Total_Time__c += entry.Logged_Time__c;            
        }  
        update timesheets.values();
    }

    public static void decrementTotalsOnTimesheet(List<Time_Entry__c> entries) {
        Set<Id> timesheetIds = new Set<Id>();
        for(Time_Entry__c entry: entries) {
            timesheetIds.add(entry.Weekly_Timesheet__c);        
        }  
        Map<Id,Weekly_Timesheet__c> timesheets = new Map<Id,Weekly_Timesheet__c> ([SELECT Id, 	Total_Time__c FROM Weekly_Timesheet__c 
                                                WHERE Id IN :timesheetIds]);
        for(Time_Entry__c entry: entries) {
            Weekly_Timesheet__c timesheet = timesheets.get(entry.Weekly_Timesheet__c);    
            timesheet.Total_Time__c -= entry.Logged_Time__c;            
        }  
        update timesheets.values();        
    }
    
}