objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project_Member__c.object
<CustomObject>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Members</relationshipLabel>
        <relationshipName>Project_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Member</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Project Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Logged_Time__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Logged Time</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Member</label>
        <referenceTo>Project_Member__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Weekly_Timesheet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Weekly Timesheet</label>
        <referenceTo>Weekly_Timesheet__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <label>WorkLog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Weekly_Timesheet__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Period_Number__c</fullName>
        <label>Period Number</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Weekly_Id__c</fullName>
        <externalId>true</externalId>
        <label>Weekly Id</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Weekly Timesheet</label>
    <nameField>
        <label>Weekly Timesheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weekly Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestUtils.cls
@isTest
public class TestUtils {
    public static Weekly_Timesheet__c createTimesheet() {
        Date newWeek = Date.today().toStartOfWeek();        
        Weekly_Timesheet__c timesheet = new Weekly_Timesheet__c();
        timesheet.OwnerId=UserInfo.getUserId();
        timesheet.Start_Date__c = newWeek;
        timesheet.End_Date__c = newWeek.addDays(6);            
        timesheet.Period_Number__c= Integer.valueOf(Datetime.newInstance(newWeek, Time.newInstance(12, 0,0,0)).format('w'));
        timesheet.Weekly_Id__c = timesheet.Period_Number__c+' '+(Id)timesheet.OwnerId;
        insert timesheet;
        return timesheet;
    }
    
    public static Time_Entry__c createTimeEntry() {
        Task__c task = createTask();
	    Time_Entry__c entry = new Time_Entry__c(Date__c=Date.today(),Logged_Time__c=10, Task__c=task.Id);
        insert entry;
        return entry;        
    }
    
    public static Time_Entry__c createTimeEntryWithoutMember() {
        Project__c project = new Project__c(Name='TestProj');
        insert project;
        Task__c task = new Task__c(Name = 'Test', Project__c=project.Id);
        insert task;
	    Time_Entry__c entry = new Time_Entry__c(Date__c=Date.today(),Logged_Time__c=10, Task__c=task.Id);
        insert entry;
        return entry;        
    }
    
    public static Task__c createTask() {
        Project__c project = new Project__c(Name='TestProj');
        insert project;
        Task__c task = new Task__c(Name = 'Test', Project__c=project.Id);
        insert task;
        Project_Member__c member = new Project_Member__c(Project__c=project.Id, Member__c=UserInfo.getUserId());
        insert member;
        return task;
    }
    
    public static List<User> createManagers(Integer count) {
        PermissionSet ps = [
                select Id
                from PermissionSet
                where Name = 'Time_Tracking_Managers'
        ];

        Profile profile = [
                select Id
                from Profile
                where Name = 'Standard User'
        ];
        List<User> testUsers = new List<User>();
        for (Integer i = 0; i < count; i++) {
            User testUser = new User(
                    alias = 'tuser' + i,
                    email = 'testuser@myexample.com' + i,
                    emailencodingkey = 'UTF-8',
                    lastname = 'Testing' + i,
                    languagelocalekey = 'en_US',
                    localesidkey = 'en_US',
                    profileid = profile.Id,
                    timezonesidkey = 'America/New_York',
                    username = 'testuser@myexample.com' + i
            );
            testUsers.add(testUser);
        }
        insert testUsers;
        List<PermissionSetAssignment> assignments = new List<PermissionSetAssignment>();
        for (User manager: testUsers) {
            PermissionSetAssignment assignment = new PermissionSetAssignment(
                    AssigneeId = manager.Id,
                    PermissionSetId = ps.Id
            );
            assignments.add(assignment);
        }
        insert assignments;
        return testUsers;
    }

}