objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Logged_Time__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Logged Time</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Timer_Started__c</fullName>
        <label>Timer Started</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Weekly_Timesheet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Weekly Timesheet</label>
        <referenceTo>Weekly_Timesheet__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>is_Timer_active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>is Timer active</label>
        <type>Checkbox</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <label>WorkLog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Weekly_Timesheet__c.object
<CustomObject>
    <label>Weekly Timesheet</label>
    <nameField>
        <label>Weekly Timesheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weekly Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TimeTrackerComponentController_Test.cls
@isTest
private class TimeTrackerComponentController_Test {

    static testmethod void getProjects_WhenUserIsNotTeamMember_EmptyList() {
        Weekly_Timesheet__c timesheet = TestUtils.createTimesheet();
                
        List<Project__c> projects = TimeTrackerComponentController.getProjects();
        System.assertEquals(0, projects.size()); 
    }  
    
    static testmethod void getProjects_WhenUserIsTeamMember_ReturnProjectsWithTasks() {
        Weekly_Timesheet__c timesheet = TestUtils.createTimesheet();
        TestUtils.createTimeEntry();
                
        List<Project__c> projects = TimeTrackerComponentController.getProjects();
        System.assertEquals(1, projects.size());
        System.assertEquals(1, projects[0].Tasks__r.size()); 
    }  
    
    static testmethod void startTimer_createTimeEntry() {
        Weekly_Timesheet__c timesheet = TestUtils.createTimesheet();
        Task__c task = TestUtils.createTask();
                
        TimeTrackerComponentController.startTimer(''+task.Id);
        
        List<Time_Entry__c> entries = [SELECT Id,is_Timer_active__c FROM Time_Entry__c];
        System.assertEquals(1, entries.size());
        System.assertEquals(true, entries[0].is_Timer_active__c); 
    }       
    
    static testmethod void stopTimer_createTimeEntry() {
        Weekly_Timesheet__c timesheet = TestUtils.createTimesheet();
        Time_Entry__c entry = TestUtils.createTimeEntry();
        entry.is_Timer_active__c=true;
        entry.Timer_Started__c=DateTime.Now().addMinutes(-15);
        update entry;        

        TimeTrackerComponentController.stopTimer(entry.Task__c);
        
        List<Time_Entry__c> entries = [SELECT Id,is_Timer_active__c,Logged_Time__c FROM Time_Entry__c];
        System.assertEquals(1, entries.size());
        System.assertEquals(false, entries[0].is_Timer_active__c); 
        System.assertEquals(25, entries[0].Logged_Time__c); // 10 set at begining + logged 15
    }     
}