objects/Weekly_Timesheet__c.object
<CustomObject>
    <fields>
        <fullName>Weekly_Id__c</fullName>
        <externalId>true</externalId>
        <label>Weekly Id</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Weekly Timesheet</label>
    <nameField>
        <label>Weekly Timesheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weekly Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WeeklyTimesheetCreatorJob_Test.cls
@isTest
private class WeeklyTimesheetCreatorJob_Test {

    static testmethod void scheduleJob_everySundayMidnight() {
        User manager = TestUtils.createManagers(5)[0];

        Test.startTest();
        System.runAs(manager) {
            String jobId = WeeklyTimesheetCreatorJob.scheduleMe();
        }
        Test.stopTest();

        List<User> managers = [SELECT Id FROM User WHERE Id IN 
                               (SELECT AssigneeId FROM PermissionSetAssignment WHERE
                               PermissionSet.Name ='Time_Tracking_Managers')];        
        List<Weekly_Timesheet__c> timesheets = [SELECT Id FROM Weekly_Timesheet__c];
        system.assertEquals(managers.size(), timesheets.size());
    }
    
    static testmethod void setWeeklyId() {
        User manager = TestUtils.createManagers(1)[0];

        Test.startTest();
        System.runAs(manager) {
            String jobId = WeeklyTimesheetCreatorJob.scheduleMe();
        }
        Test.stopTest();
    
        Weekly_Timesheet__c timesheet = [SELECT Id, Weekly_Id__c FROM Weekly_Timesheet__c WHERE OwnerId=:manager.Id];
        String properId = Integer.valueOf(Datetime.newInstance(Date.today().toStartOfWeek().addDays(7), 
                                                               Time.newInstance(12, 0,0,0)).format('w')) +' '+manager.Id;
        system.assertEquals(properId, timesheet.Weekly_Id__c);
    }    
}